INSERT INTO CATEGORIE (ID_CATEGORIE, NOM_CATEGORIE) VALUES (1, 'Bois');
INSERT INTO CATEGORIE (ID_CATEGORIE, NOM_CATEGORIE) VALUES (2, 'Metal');
INSERT INTO CATEGORIE (ID_CATEGORIE, NOM_CATEGORIE) VALUES (3, 'Plastique');
INSERT INTO CATEGORIE (ID_CATEGORIE, NOM_CATEGORIE) VALUES (4, 'Verre');
INSERT INTO CATEGORIE (ID_CATEGORIE, NOM_CATEGORIE) VALUES (5, 'Textile');
INSERT INTO CATEGORIE (ID_CATEGORIE, NOM_CATEGORIE) VALUES (6, 'Beton');
INSERT INTO CATEGORIE (ID_CATEGORIE, NOM_CATEGORIE) VALUES (7, 'Caoutchouc');


INSERT INTO UTILISATEUR (ID_USER, ID_ENTREP, NOM_USER, PRENOM_USER, EMAIL_USER, TELEPHONE_USER, MOT_DE_PASSE_USER, TYPE_USER, ADRESSE_USER, VILLE_USER, DATE_INSCRIPTION_USER)
   VALUES (1, NULL, 'Ben Ali', 'Ahmed', 'ahmed.benali@gmail.com', '21612345678', 'hashed_pwd_1', 'particulier', '12 Rue de la Paix', 'Tunis', TO_DATE('2024-01-10', 'YYYY-MM-DD'));
INSERT INTO UTILISATEUR (ID_USER, ID_ENTREP, NOM_USER, PRENOM_USER, EMAIL_USER, TELEPHONE_USER, MOT_DE_PASSE_USER, TYPE_USER, ADRESSE_USER, VILLE_USER, DATE_INSCRIPTION_USER)
   VALUES (2, NULL, 'Trabelsi', 'Sonia', 'sonia.trabelsi@gmail.com', '21623456789', 'hashed_pwd_2', 'artisan', '45 Avenue Habib Bourguiba', 'Sfax', TO_DATE('2024-02-15', 'YYYY-MM-DD'));
INSERT INTO UTILISATEUR (ID_USER, ID_ENTREP, NOM_USER, PRENOM_USER, EMAIL_USER, TELEPHONE_USER, MOT_DE_PASSE_USER, TYPE_USER, ADRESSE_USER, VILLE_USER, DATE_INSCRIPTION_USER)
   VALUES (3, NULL, 'Mansouri', 'Karim', 'karim.mansouri@ecobat.tn', '21634567890', 'hashed_pwd_3', 'entreprise', '10 Rue de l industrie', 'Bizerte', TO_DATE('2024-03-01', 'YYYY-MM-DD'));
INSERT INTO UTILISATEUR (ID_USER, ID_ENTREP, NOM_USER, PRENOM_USER, EMAIL_USER, TELEPHONE_USER, MOT_DE_PASSE_USER, TYPE_USER, ADRESSE_USER, VILLE_USER, DATE_INSCRIPTION_USER)
   VALUES (4, NULL, 'Chabbi', 'Nour', 'nour.chabbi@recyclpro.tn', '21645678901', 'hashed_pwd_4', 'entreprise', '7 Zone Industrielle', 'Sousse', TO_DATE('2024-03-20', 'YYYY-MM-DD'));
INSERT INTO UTILISATEUR (ID_USER, ID_ENTREP, NOM_USER, PRENOM_USER, EMAIL_USER, TELEPHONE_USER, MOT_DE_PASSE_USER, TYPE_USER, ADRESSE_USER, VILLE_USER, DATE_INSCRIPTION_USER)
   VALUES (5, NULL, 'Hamdi', 'Youssef', 'youssef.hamdi@metalvert.tn', '21656789012', 'hashed_pwd_5', 'entreprise', '33 Rue des Fonderies', 'Nabeul', TO_DATE('2024-04-05', 'YYYY-MM-DD'));
INSERT INTO UTILISATEUR (ID_USER, ID_ENTREP, NOM_USER, PRENOM_USER, EMAIL_USER, TELEPHONE_USER, MOT_DE_PASSE_USER, TYPE_USER, ADRESSE_USER, VILLE_USER, DATE_INSCRIPTION_USER)
   VALUES (6, NULL, 'Jebali', 'Fatma', 'fatma.jebali@boisdurable.tn', '21667890123', 'hashed_pwd_6', 'entreprise', '2 Rue des Artisans', 'Monastir', TO_DATE('2024-04-18', 'YYYY-MM-DD'));
INSERT INTO UTILISATEUR (ID_USER, ID_ENTREP, NOM_USER, PRENOM_USER, EMAIL_USER, TELEPHONE_USER, MOT_DE_PASSE_USER, TYPE_USER, ADRESSE_USER, VILLE_USER, DATE_INSCRIPTION_USER)
   VALUES (7, NULL, 'Bouri', 'Amine', 'amine.bouri@greentex.tn', '21678901234', 'hashed_pwd_7', 'entreprise', '15 Avenue de la Republique', 'Gabes', TO_DATE('2024-05-02', 'YYYY-MM-DD'));
INSERT INTO UTILISATEUR (ID_USER, ID_ENTREP, NOM_USER, PRENOM_USER, EMAIL_USER, TELEPHONE_USER, MOT_DE_PASSE_USER, TYPE_USER, ADRESSE_USER, VILLE_USER, DATE_INSCRIPTION_USER)
   VALUES (8, NULL, 'Admin', 'System', 'admin@platform.tn', '21689012345', 'hashed_pwd_8', 'admin', '1 Rue Admin', 'Tunis', TO_DATE('2024-01-01', 'YYYY-MM-DD'));

INSERT INTO ENTREPRISE (ID_ENTREP, ID_USER, NOM_ENTREP, SECTEUR_ACTIVITE_ENTREP, MATRICULE_FISCALE_ENTREP)
   VALUES (1, 3, 'EcoBat SARL', 'Construction', 'MF100123456');
INSERT INTO ENTREPRISE (ID_ENTREP, ID_USER, NOM_ENTREP, SECTEUR_ACTIVITE_ENTREP, MATRICULE_FISCALE_ENTREP)
   VALUES (2, 4, 'RecyclPro', 'Recyclage', 'MF200234567');
INSERT INTO ENTREPRISE (ID_ENTREP, ID_USER, NOM_ENTREP, SECTEUR_ACTIVITE_ENTREP, MATRICULE_FISCALE_ENTREP)
   VALUES (3, 5, 'MetalVert SA', 'Industrie metallurgique', 'MF300345678');
INSERT INTO ENTREPRISE (ID_ENTREP, ID_USER, NOM_ENTREP, SECTEUR_ACTIVITE_ENTREP, MATRICULE_FISCALE_ENTREP)
   VALUES (4, 6, 'BoisDurable', 'Menuiserie', 'MF400456789');
INSERT INTO ENTREPRISE (ID_ENTREP, ID_USER, NOM_ENTREP, SECTEUR_ACTIVITE_ENTREP, MATRICULE_FISCALE_ENTREP)
   VALUES (5, 7, 'GreenTex', 'Textile', 'MF500567890');


UPDATE UTILISATEUR SET ID_ENTREP = 1 WHERE ID_USER = 3;
UPDATE UTILISATEUR SET ID_ENTREP = 2 WHERE ID_USER = 4;
UPDATE UTILISATEUR SET ID_ENTREP = 3 WHERE ID_USER = 5;
UPDATE UTILISATEUR SET ID_ENTREP = 4 WHERE ID_USER = 6;
UPDATE UTILISATEUR SET ID_ENTREP = 5 WHERE ID_USER = 7;


INSERT INTO IMPACT_ENVIROMMENTAL (ID_IMPACT, ID_MATERIAU, DECHETS_EVITE_KG_IMPACT, CO2_ECONOMISE_KG_IMPACT, DATE_IMPACT)
   VALUES (1, NULL, 150.50, 75.25, TIMESTAMP '2024-06-01 10:00:00');
INSERT INTO IMPACT_ENVIROMMENTAL (ID_IMPACT, ID_MATERIAU, DECHETS_EVITE_KG_IMPACT, CO2_ECONOMISE_KG_IMPACT, DATE_IMPACT)
   VALUES (2, NULL, 200.00, 100.00, TIMESTAMP '2024-06-10 14:30:00');
INSERT INTO IMPACT_ENVIROMMENTAL (ID_IMPACT, ID_MATERIAU, DECHETS_EVITE_KG_IMPACT, CO2_ECONOMISE_KG_IMPACT, DATE_IMPACT)
   VALUES (3, NULL, 80.75, 40.50, TIMESTAMP '2024-07-05 09:15:00');
INSERT INTO IMPACT_ENVIROMMENTAL (ID_IMPACT, ID_MATERIAU, DECHETS_EVITE_KG_IMPACT, CO2_ECONOMISE_KG_IMPACT, DATE_IMPACT)
   VALUES (4, NULL, 320.00, 160.00, TIMESTAMP '2024-07-20 16:45:00');
INSERT INTO IMPACT_ENVIROMMENTAL (ID_IMPACT, ID_MATERIAU, DECHETS_EVITE_KG_IMPACT, CO2_ECONOMISE_KG_IMPACT, DATE_IMPACT)
   VALUES (5, NULL, 50.25, 25.10, TIMESTAMP '2024-08-01 11:00:00');
INSERT INTO IMPACT_ENVIROMMENTAL (ID_IMPACT, ID_MATERIAU, DECHETS_EVITE_KG_IMPACT, CO2_ECONOMISE_KG_IMPACT, DATE_IMPACT)
   VALUES (6, NULL, 110.00, 55.00, TIMESTAMP '2024-08-15 08:30:00');
INSERT INTO IMPACT_ENVIROMMENTAL (ID_IMPACT, ID_MATERIAU, DECHETS_EVITE_KG_IMPACT, CO2_ECONOMISE_KG_IMPACT, DATE_IMPACT)
   VALUES (7, NULL, 95.00, 47.50, TIMESTAMP '2024-08-20 13:00:00');
INSERT INTO IMPACT_ENVIROMMENTAL (ID_IMPACT, ID_MATERIAU, DECHETS_EVITE_KG_IMPACT, CO2_ECONOMISE_KG_IMPACT, DATE_IMPACT)
   VALUES (8, NULL, 60.00, 30.00, TIMESTAMP '2024-09-01 09:00:00');


INSERT INTO MATERIAU (ID_MATERIAU, ID_CATEGORIE, ID_USER, ID_IMPACT, NOM_MATERIAU, DESCRIPTIN_MATERIAU, ETAT_MATERIAU, QUANTITE_MATERIAU, DIMENSIONS_MATERIAU, MODE_ECHANGE_MATERIAU, DISPONIBLITE_MATERIAU, DATE_PUBLICATION_MATERIAU, PRIX_MATERIAU)
   VALUES (1, 1, 1, 1, 'Planches de bois', 'Planches de chene recyclees en bon etat', 'bon', 50, '200x20x5 cm', 'vente', 'disponible', TO_DATE('2024-06-02', 'YYYY-MM-DD'), 150.00);
INSERT INTO MATERIAU (ID_MATERIAU, ID_CATEGORIE, ID_USER, ID_IMPACT, NOM_MATERIAU, DESCRIPTIN_MATERIAU, ETAT_MATERIAU, QUANTITE_MATERIAU, DIMENSIONS_MATERIAU, MODE_ECHANGE_MATERIAU, DISPONIBLITE_MATERIAU, DATE_PUBLICATION_MATERIAU, PRIX_MATERIAU)
   VALUES (2, 2, 2, 2, 'Profiles acier', 'Profiles en acier galvanise recuperes', 'moyen', 30, '300x10x10 cm', 'don', 'disponible', TO_DATE('2024-06-11', 'YYYY-MM-DD'), 0.00);
INSERT INTO MATERIAU (ID_MATERIAU, ID_CATEGORIE, ID_USER, ID_IMPACT, NOM_MATERIAU, DESCRIPTIN_MATERIAU, ETAT_MATERIAU, QUANTITE_MATERIAU, DIMENSIONS_MATERIAU, MODE_ECHANGE_MATERIAU, DISPONIBLITE_MATERIAU, DATE_PUBLICATION_MATERIAU, PRIX_MATERIAU)
   VALUES (3, 3, 1, 3, 'Granules plastique', 'Granules de PVC recycle', 'bon', 100, NULL, 'vente', 'disponible', TO_DATE('2024-07-06', 'YYYY-MM-DD'), 80.00);
INSERT INTO MATERIAU (ID_MATERIAU, ID_CATEGORIE, ID_USER, ID_IMPACT, NOM_MATERIAU, DESCRIPTIN_MATERIAU, ETAT_MATERIAU, QUANTITE_MATERIAU, DIMENSIONS_MATERIAU, MODE_ECHANGE_MATERIAU, DISPONIBLITE_MATERIAU, DATE_PUBLICATION_MATERIAU, PRIX_MATERIAU)
   VALUES (4, 4, 2, 4, 'Vitres doubles', 'Vitres de fenetres recuperees de chantier', 'bon', 20, '120x80 cm', 'troc', 'disponible', TO_DATE('2024-07-21', 'YYYY-MM-DD'), 200.00);
INSERT INTO MATERIAU (ID_MATERIAU, ID_CATEGORIE, ID_USER, ID_IMPACT, NOM_MATERIAU, DESCRIPTIN_MATERIAU, ETAT_MATERIAU, QUANTITE_MATERIAU, DIMENSIONS_MATERIAU, MODE_ECHANGE_MATERIAU, DISPONIBLITE_MATERIAU, DATE_PUBLICATION_MATERIAU, PRIX_MATERIAU)
   VALUES (5, 5, 1, 5, 'Rouleaux tissu', 'Rouleaux de tissu coton non utilises', 'neuf', 15, '150x100 cm', 'vente', 'disponible', TO_DATE('2024-08-02', 'YYYY-MM-DD'), 60.00);
INSERT INTO MATERIAU (ID_MATERIAU, ID_CATEGORIE, ID_USER, ID_IMPACT, NOM_MATERIAU, DESCRIPTIN_MATERIAU, ETAT_MATERIAU, QUANTITE_MATERIAU, DIMENSIONS_MATERIAU, MODE_ECHANGE_MATERIAU, DISPONIBLITE_MATERIAU, DATE_PUBLICATION_MATERIAU, PRIX_MATERIAU)
   VALUES (6, 6, 2, 6, 'Parpaings beton', 'Parpaings recuperes de demolition', 'moyen', 200, '20x20x40 cm', 'don', 'disponible', TO_DATE('2024-08-16', 'YYYY-MM-DD'), 0.00);
INSERT INTO MATERIAU (ID_MATERIAU, ID_CATEGORIE, ID_USER, ID_IMPACT, NOM_MATERIAU, DESCRIPTIN_MATERIAU, ETAT_MATERIAU, QUANTITE_MATERIAU, DIMENSIONS_MATERIAU, MODE_ECHANGE_MATERIAU, DISPONIBLITE_MATERIAU, DATE_PUBLICATION_MATERIAU, PRIX_MATERIAU)
   VALUES (7, 2, 1, 7, 'Tuyaux cuivre', 'Tuyaux en cuivre de plomberie', 'bon', 40, '200x2 cm', 'vente', 'reserve', TO_DATE('2024-08-20', 'YYYY-MM-DD'), 300.00);
INSERT INTO MATERIAU (ID_MATERIAU, ID_CATEGORIE, ID_USER, ID_IMPACT, NOM_MATERIAU, DESCRIPTIN_MATERIAU, ETAT_MATERIAU, QUANTITE_MATERIAU, DIMENSIONS_MATERIAU, MODE_ECHANGE_MATERIAU, DISPONIBLITE_MATERIAU, DATE_PUBLICATION_MATERIAU, PRIX_MATERIAU)
   VALUES (8, 7, 2, 8, 'Joints caoutchouc', 'Joints industriels en caoutchouc naturel', 'neuf', 500, '5x5 cm', 'vente', 'disponible', TO_DATE('2024-09-01', 'YYYY-MM-DD'), 25.00);

UPDATE IMPACT_ENVIROMMENTAL SET ID_MATERIAU = 1 WHERE ID_IMPACT = 1;
UPDATE IMPACT_ENVIROMMENTAL SET ID_MATERIAU = 2 WHERE ID_IMPACT = 2;
UPDATE IMPACT_ENVIROMMENTAL SET ID_MATERIAU = 3 WHERE ID_IMPACT = 3;
UPDATE IMPACT_ENVIROMMENTAL SET ID_MATERIAU = 4 WHERE ID_IMPACT = 4;
UPDATE IMPACT_ENVIROMMENTAL SET ID_MATERIAU = 5 WHERE ID_IMPACT = 5;
UPDATE IMPACT_ENVIROMMENTAL SET ID_MATERIAU = 6 WHERE ID_IMPACT = 6;
UPDATE IMPACT_ENVIROMMENTAL SET ID_MATERIAU = 7 WHERE ID_IMPACT = 7;
UPDATE IMPACT_ENVIROMMENTAL SET ID_MATERIAU = 8 WHERE ID_IMPACT = 8;

INSERT INTO RESERVATION (ID_RESERVATION, ID_MATERIAU, ID_USER, DATE_RESERVATION, STATUT_RESERVATION)
   VALUES (1, 1, 2, TO_DATE('2024-06-05', 'YYYY-MM-DD'), 'confirmee');
INSERT INTO RESERVATION (ID_RESERVATION, ID_MATERIAU, ID_USER, DATE_RESERVATION, STATUT_RESERVATION)
   VALUES (2, 3, 2, TO_DATE('2024-07-08', 'YYYY-MM-DD'), 'en attente');
INSERT INTO RESERVATION (ID_RESERVATION, ID_MATERIAU, ID_USER, DATE_RESERVATION, STATUT_RESERVATION)
   VALUES (3, 5, 1, TO_DATE('2024-08-03', 'YYYY-MM-DD'), 'confirmee');
INSERT INTO RESERVATION (ID_RESERVATION, ID_MATERIAU, ID_USER, DATE_RESERVATION, STATUT_RESERVATION)
   VALUES (4, 2, 1, TO_DATE('2024-08-10', 'YYYY-MM-DD'), 'annulee');
INSERT INTO RESERVATION (ID_RESERVATION, ID_MATERIAU, ID_USER, DATE_RESERVATION, STATUT_RESERVATION)
   VALUES (5, 6, 1, TO_DATE('2024-08-18', 'YYYY-MM-DD'), 'en attente');
INSERT INTO RESERVATION (ID_RESERVATION, ID_MATERIAU, ID_USER, DATE_RESERVATION, STATUT_RESERVATION)
   VALUES (6, 7, 2, TO_DATE('2024-08-22', 'YYYY-MM-DD'), 'confirmee');
INSERT INTO RESERVATION (ID_RESERVATION, ID_MATERIAU, ID_USER, DATE_RESERVATION, STATUT_RESERVATION)
   VALUES (7, 4, 1, TO_DATE('2024-09-02', 'YYYY-MM-DD'), 'en attente');

INSERT INTO MESSAGE (ID_MESSAGE, ID_USER, UTI_ID_USER, CONTENU_MESSAGE, DATE_ENVOI_MESSAGE)
   VALUES (1, 2, 1, 'Bonjour, les planches sont-elles encore disponibles ?', TIMESTAMP '2024-06-03 09:00:00');
INSERT INTO MESSAGE (ID_MESSAGE, ID_USER, UTI_ID_USER, CONTENU_MESSAGE, DATE_ENVOI_MESSAGE)
   VALUES (2, 1, 2, 'Oui, toujours disponibles. Contactez-moi pour les details.', TIMESTAMP '2024-06-03 10:15:00');
INSERT INTO MESSAGE (ID_MESSAGE, ID_USER, UTI_ID_USER, CONTENU_MESSAGE, DATE_ENVOI_MESSAGE)
   VALUES (3, 1, 2, 'Je suis interesse par vos profiles acier.', TIMESTAMP '2024-06-12 08:30:00');
INSERT INTO MESSAGE (ID_MESSAGE, ID_USER, UTI_ID_USER, CONTENU_MESSAGE, DATE_ENVOI_MESSAGE)
   VALUES (4, 2, 1, 'Merci de votre interet, venez les recuperer demain.', TIMESTAMP '2024-06-12 11:00:00');
INSERT INTO MESSAGE (ID_MESSAGE, ID_USER, UTI_ID_USER, CONTENU_MESSAGE, DATE_ENVOI_MESSAGE)
   VALUES (5, 2, 1, 'Quel est le prix pour 5 rouleaux de tissu ?', TIMESTAMP '2024-08-04 14:00:00');
INSERT INTO MESSAGE (ID_MESSAGE, ID_USER, UTI_ID_USER, CONTENU_MESSAGE, DATE_ENVOI_MESSAGE)
   VALUES (6, 1, 2, 'Pour 5 rouleaux, je vous fais 250 DT.', TIMESTAMP '2024-08-04 15:30:00');
INSERT INTO MESSAGE (ID_MESSAGE, ID_USER, UTI_ID_USER, CONTENU_MESSAGE, DATE_ENVOI_MESSAGE)
   VALUES (7, 1, 2, 'Pouvez-vous livrer les parpaings a Sfax ?', TIMESTAMP '2024-08-17 09:45:00');
INSERT INTO MESSAGE (ID_MESSAGE, ID_USER, UTI_ID_USER, CONTENU_MESSAGE, DATE_ENVOI_MESSAGE)
   VALUES (8, 2, 1, 'Desole, pas de livraison, recuperation sur place uniquement.', TIMESTAMP '2024-08-17 10:20:00');

INSERT INTO SIGNALEMENT (ID_SIGNALEMENT, ID_MATERIAU, ID_USER, MOTIF_SIGNALEMENT, DATE_SINGALEMENT)
   VALUES (1, 3, 2, 'Description incorrecte, les granules ne sont pas en bon etat.', TO_DATE('2024-07-10', 'YYYY-MM-DD'));
INSERT INTO SIGNALEMENT (ID_SIGNALEMENT, ID_MATERIAU, ID_USER, MOTIF_SIGNALEMENT, DATE_SINGALEMENT)
   VALUES (2, 7, 2, 'Prix trop eleve par rapport a la qualite annoncee.', TO_DATE('2024-08-25', 'YYYY-MM-DD'));
INSERT INTO SIGNALEMENT (ID_SIGNALEMENT, ID_MATERIAU, ID_USER, MOTIF_SIGNALEMENT, DATE_SINGALEMENT)
   VALUES (3, 4, 1, 'Les dimensions indiquees ne correspondent pas a la realite.', TO_DATE('2024-07-22', 'YYYY-MM-DD'));
INSERT INTO SIGNALEMENT (ID_SIGNALEMENT, ID_MATERIAU, ID_USER, MOTIF_SIGNALEMENT, DATE_SINGALEMENT)
   VALUES (4, 8, 1, 'Annonce dupliquee, materiau deja publie par un autre utilisateur.', TO_DATE('2024-09-03', 'YYYY-MM-DD'));
INSERT INTO SIGNALEMENT (ID_SIGNALEMENT, ID_MATERIAU, ID_USER, MOTIF_SIGNALEMENT, DATE_SINGALEMENT)
   VALUES (5, 1, 2, 'Vendeur ne repond plus aux messages depuis 2 semaines.', TO_DATE('2024-09-05', 'YYYY-MM-DD'));

COMMIT;
